export const UPLOADER_OPEN_DIALOG = 'UPLOADER_OPEN_DIALOG';
export const UPLOADER_CLOSE_DIALOG = 'UPLOADER_CLOSE_DIALOG';
export const UPLOADER_CHANGE_FILE = 'UPLOADER_CHANGE_FILE';
export const UPLOADER_SUBMIT_FILE_BEGIN = 'UPLOADER_SUBMIT_FILE_BEGIN';
export const UPLOADER_SUBMIT_FILE_SUCCESS = 'UPLOADER_SUBMIT_FILE_SUCCESS';
export const UPLOADER_SUBMIT_FILE_FAILURE = 'UPLOADER_SUBMIT_FILE_FAILURE';
export const UPLOADER_SUBMIT_FILE_DISMISS_ERROR = 'UPLOADER_SUBMIT_FILE_DISMISS_ERROR';
