export const HOME_HANDLE_DROP_BEGIN = 'HOME_HANDLE_DROP_BEGIN';
export const HOME_HANDLE_DROP_SUCCESS = 'HOME_HANDLE_DROP_SUCCESS';
export const HOME_HANDLE_DROP_FAILURE = 'HOME_HANDLE_DROP_FAILURE';
export const HOME_HANDLE_DROP_DISMISS_ERROR = 'HOME_HANDLE_DROP_DISMISS_ERROR';
