export const LAYER_ADD_LAYER = 'LAYER_ADD_LAYER';
export const LAYER_MINIMIZE_LAYER_DIV = 'LAYER_MINIMIZE_LAYER_DIV';
export const LAYER_MAXIMIZE_LAYER_DIV = 'LAYER_MAXIMIZE_LAYER_DIV';
export const LAYER_UPDATE_LAYER = 'LAYER_UPDATE_LAYER';
